/*
  app.js -- This creates an Express webserver with login/register/logout authentication
*/

// *********************************************************** //
//  Loading packages to support the server
// *********************************************************** //
// First we load in all of the packages we need for the server...
const createError = require("http-errors"); // to handle the server errors
const express = require("express");
const path = require("path");  // to refer to local paths
const cookieParser = require("cookie-parser"); // to handle cookies
const session = require("express-session"); // to handle sessions using cookies
const debug = require("debug")("personalapp:server"); 
const layouts = require("express-ejs-layouts");

const axios = require("axios");


// *********************************************************** //
//  Loading models
// *********************************************************** //
const WishList = require("./models/WishList.js")

// *********************************************************** //
//  Loading API
// *********************************************************** //
const API_KEY = process.env.API_KEY;

// *********************************************************** //
//  Connecting to the database
// *********************************************************** //
const mongoose = require( 'mongoose' );
const mongodb_URI = process.env.mongodb_URI


mongoose.connect( mongodb_URI, { useNewUrlParser: true, useUnifiedTopology: true } );
// fix deprecation warnings
mongoose.set('useFindAndModify', false); 
mongoose.set('useCreateIndex', true);

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {console.log("we are connected!!!")});


// *********************************************************** //
// Initializing the Express server 
// This code is run once when the app is started and it creates
// a server that respond to requests by sending responses
// *********************************************************** //
const app = express();

// Here we specify that we will be using EJS as our view engine
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");



// this allows us to use page layout for the views 
// so we don't have to repeat the headers and footers on every page ...
// the layout is in views/layout.ejs
app.use(layouts);

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling using cookies
app.use(
  session({
    secret: "zzbbyanana789sdfa8f9ds8f90ds87f8d9s789fds", // this ought to be hidden in process.env.SECRET
    resave: false,
    saveUninitialized: false
  })
);

// *********************************************************** //
//  Defining the routes the Express server will respond to
// *********************************************************** //


// here is the code which handles all /login /signin /logout routes
// here is the code which handles all /login /signin /logout routes
const auth = require('./routes/auth');
// here is the code which handles all /login /signin /logout routes
const wishlist = require('./routes/wishlist');
const { deflateSync } = require("zlib");
app.use(auth,wishlist);

// middleware to test is the user is logged in, and if not, send them to the login page
const isLoggedIn = (req,res,next) => {
  if (res.locals.loggedIn) {
    next()
  }
  else res.redirect('/login')
}

// specify that the server should render the views/index.ejs page for the root path
// and the index.ejs code will be wrapped in the views/layouts.ejs code which provides
// the headers and footers for all webpages generated by this app
app.get("/", (req, res, next) => {
  res.render("index");
});

app.get("/about", (req, res, next) => {
  res.render("about");
});


/* ************************
  Loading (or reloading) the data into a collection
   ************************ */
// this route loads in the books into the Book collection
// or updates the books if it is not a new collection

//search for books
app.post('/books/search',
  async (req,res,next) => {
    try{
    const{title, author}=req.body;
    const response = await axios.get("https://www.googleapis.com/books/v1/volumes?q=intitle:"+title+"+inauthor:"+author+"&maxResults=20&key="+API_KEY)
    
    res.locals.titleRes=response.data.items.map(x => x['volumeInfo']['title'])
    res.locals.authorRes=response.data.items.map(x => x['volumeInfo']['authors'])
    res.locals.descriptionRes=response.data.items.map(x => x['volumeInfo']['description'])
    res.locals.imageRes=response.data.items.map(x => x['volumeInfo']['imageLinks']['thumbnail'])
    if(checkNested(response.data.items,"volumeInfo","imageLinks","thumbnail")){
      res.locals.imageRes=response.data.items.map(x => x['volumeInfo']['imageLinks']['thumbnail'])
    }
    res.locals.isbnRes=response.data.items.map(x => x['volumeInfo']['industryIdentifiers'][0]['identifier'])
    res.render('booklist')
    }catch (error) {
      res.render('errorsearch.ejs')
    }
  })

//shows the description of the book
app.get('/books/show/:isbn',
  // show all info about a course given its courseid
  async (req,res,next) => {
    const {isbn} = req.params;
    const response = await axios.get("https://www.googleapis.com/books/v1/volumes?q="+isbn+"&maxResults=20&key="+API_KEY)
    if(!response.data.items){
      res.render('errorsearch.ejs')
    }
    res.locals.title = response.data.items[0]['volumeInfo']['title']
    res.locals.author=response.data.items[0]['volumeInfo']['authors']
    
    res.locals.description=response.data.items[0]['volumeInfo']['description']
    if(checkNested(response.data.items[0],"volumeInfo","imageLinks","thumbnail")){
      res.locals.image=response.data.items[0]['volumeInfo']['imageLinks']['thumbnail']
    }
    res.locals.isbn=isbn
    //res.json(course)
    res.render('book')

  }
)

// *********************************************************** //
//  Starting up the server!
// *********************************************************** //
//Here we set the port to use between 1024 and 65535  (2^16-1)
const port = process.env.PORT || "5000";
console.log('connecting on port '+port)
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const { resourceLimits } = require("worker_threads");
const server = http.createServer(app);

server.listen(port);

function onListening() {
  var addr = server.address();
  var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
  debug("Listening on " + bind);
}
function checkNested(obj /*, level1, level2, ... levelN*/) {
  var args = Array.prototype.slice.call(arguments, 1);

  for (var i = 0; i < args.length; i++) {
    if (!obj || !obj.hasOwnProperty(args[i])) {
      return false;
    }
    obj = obj[args[i]];
  }
  return true;
}
function onError(error) {
  if (error.syscall !== "listen") {
    throw error;
  }

  var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case "EACCES":
      console.error(bind + " requires elevated privileges");
      process.exit(1);
      break;
    case "EADDRINUSE":
      console.error(bind + " is already in use");
      process.exit(1);
      break;
    default:
      throw error;
  }
}

server.on("error", onError);

server.on("listening", onListening);

module.exports = app;